let container1 = document.querySelector(".container") as HTMLDivElement;
let container2 = document.querySelector(".container1") as HTMLDivElement;
let subit_btn = document.querySelector(".resumeGeneratbtn") as HTMLInputElement;

// Forms-Input

let names = document.querySelector(".name") as HTMLInputElement;
let designation = document.querySelector(".designation") as HTMLInputElement;
let email = document.querySelector(".email") as HTMLInputElement;
let Linkedin = document.querySelector(".Linkedin") as HTMLInputElement;
let github = document.querySelector(".github") as HTMLInputElement;
let locations = document.querySelector(".location") as HTMLInputElement;
let school = document.querySelector(".school") as HTMLInputElement;
let Degree = document.querySelector(".Degree") as HTMLInputElement;
let College = document.querySelector(".College") as HTMLInputElement;
let html = document.querySelector(".html") as HTMLInputElement;
let css = document.querySelector(".css") as HTMLInputElement;
let rjs = document.querySelector(".rjs") as HTMLInputElement;
let ty = document.querySelector(".ty") as HTMLInputElement;
let image_upload_path = document.querySelector(
  ".image-upload"
) as HTMLInputElement; // here we will get the file we choose to upload image
let aboutMe = document.querySelector(".aboutMe") as HTMLTextAreaElement;
let yearOfSchool = document.querySelector(".yearOfSchool") as HTMLInputElement;
let yearOfCollege = document.querySelector(
  ".yearOfCollege"
) as HTMLInputElement;
let ph = document.querySelector(".ph") as HTMLInputElement;
let insitution = document.querySelector(".insitution") as HTMLInputElement;
let experience = document.querySelector(".experience") as HTMLInputElement;

let btn = document.querySelector(".button") as HTMLDivElement;
let editbtn = document.querySelector("#go-back") as HTMLButtonElement;
let downloadbtn = document.querySelector("#Download") as HTMLButtonElement;
let Linkbtn = document.querySelector("#Linkbtn") as HTMLButtonElement;

// !getting IMAGE

const image = document.querySelector(".img-box img") as HTMLImageElement;
// The change event in JavaScript is triggered when the value of an input, select, or textarea element changes and the user "commits" the change. This typically occurs when:
// When you select a new file in an <input type="file"> element, the change event is triggered. This is commonly used for tasks like displaying a preview of an
//image or video file that the user has selected.

//? when this event target we will create a url for the image that has chosen and put that url in src of img
image_upload_path.addEventListener("change", (e) => {
  const file = e.target as HTMLInputElement;
  let path: any = file.files?.[0];

  if (path) {
    image.src = URL.createObjectURL(path); // The upper img varaible has a image init with a scr <img src="4843806.jpg" alt="Profile Picture"> so the url generated by this {img.src =  URL.createObjectURL(path)}  will added  inside
    //  this <img src="img.src" alt="Profile Picture">
    //   console.log(image.src);
  }
});
//!



//! on click Resume will be generated
subit_btn.addEventListener("click", (e) => {
  e.preventDefault();
  if (
    names.value.trim() === "" ||
    designation.value.trim() === "" ||
    email.value.trim() === "" ||
    Linkedin.value.trim() === "" ||
    github.value.trim() === "" ||
    locations.value.trim() === "" ||
    school.value.trim() === "" ||
    Degree.value.trim() === "" ||
    College.value.trim() === "" ||
    html.value.trim() === "" ||
    css.value.trim() === "" ||
    rjs.value.trim() === "" ||
    ty.value.trim() === "" ||
    image_upload_path.value === "" ||
    aboutMe.value === "" ||
    yearOfCollege.value === "" ||
    yearOfSchool.value === "" ||
    ph.value === "" ||
    insitution.value === ""
  ) {
    alert("Please fill all the fields");
  } else {
    container2.classList.remove("hidden");
    btn.classList.remove("hidden2");
    container1.classList.add("hidden");
    document.body.style.backgroundColor = "#fefae0";

    container2.innerHTML = `
  <div class="left-side">
            <div class="profiletext">
                <div class="img-box">
                    <img src=${image.src} alt="Profile Picture">
                </div>
                <h2>${names.value}<br><span>${designation.value}</span></h2>
            </div>
            <div class="contact">
                <h3 class="title">Contact Info</h3>
                <ul>
                    <li>
                        <span class="icon"><i class="fa fa-phone" aria-hidden="true"></i></span>
                        <span class="text">${ph.value}</span>
                        <br>
                    </li>
                    <li>
                        <span class="icon"><i class="fa fa-envelope" aria-hidden="true"></i></span>
                        <span class="text">${email.value}</span>
                        <br>
                    </li>
                    <li>
                        <span class="icon"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span>
                        <span class="text"><a href=${Linkedin.value}>Linkedin</a></span>
                        <br>
                    </li>
                    <li>
                        <span class="icon"><i class="fa fa-github-square" aria-hidden="true"></i></span>
                        <span class="text"><a
                                href=${github.value}>GitHub</a></span>
                        <br>
                    </li>
                    <li>
                        <span class="icon"> <i class="fa fa-map-marker" aria-hidden="true"></i></span>
                        <span class="text">${locations.value}</span>
                        <br>
                    </li>
                </ul>
            </div>

            <!-- Education -->

            <div class="contact Education">
                <h3 class="title">Education</h3>
                <ul>
                    <li>
                        <h5>${yearOfSchool.value}</h5>
                        <h4>Matriculation</h4>
                        <h4>School Name : ${school.value}</h4>
                    </li>
                    <li>
                        <h5>2020 - 2022</h5>
                        <h4>Intermediate</h4>
                        <h4>College Name : ${College.value}</h4>
                    </li>
                    <li>
                        <h5>2022 - 2023</h5>
                        <h4>Gen AI, Web3.0, Metaverse </h4>
                        <h4>Instituion name : ${insitution.value}</h4>
                    </li>
                </ul>
            </div>
        </div>



        <div class="right-side">

            <div class="aboutme">
                <h2 class="title2">About <span class="me">Me</span></h2>
                <p>${aboutMe.value}</p>
            </div>

            <!-- experience -->

            <div class="experience">
                <h2 class="title2">My <span class="me"> Experience</span></h2>
                <p>${experience.value}</p>
            </div>


            <!-- skills -->

            <div class="skills">
                <h2 class="title2">Professional <span class="me">Skills</span></h2>
                <div class="box">
                    <h4>HTML</h4>
                    <div class="percentage">
                        <div style="width: ${html.value};"></div>
                    </div>
                </div>

                <div class="box">
                    <h4>CSS</h4>
                    <div class="percentage">
                        <div style="width: ${css.value};"></div>
                    </div>
                </div>
            </div>

            <div class="box">
                <h4>Typescript</h4>
                <div class="percentage">
                    <div style="width: ${ty.value};"></div>
                </div>
            </div>

            <div class="box">
                <h4>React.js</h4>
                <div class="percentage">
                    <div style="width: ${rjs.value};"></div>
                </div>
            </div>

            
            <h3 class="water-mark">Resume builder by <span class="title">Muhammad Azan</span></h3> `;
  }
});

//! Editable button for Resume
editbtn.addEventListener("click", () => {
  container2.classList.add("hidden");
  container1.classList.remove("hidden");
  btn.classList.add("hidden2");
  document.body.style.backgroundColor = "#2252b8";
});

//!Donwload button for resume
declare const html2pdf: any;
downloadbtn.addEventListener("click", () => {
  if (typeof html2pdf === "undefined") {
    alert("ERORR: Html2Pdf library is not loaded");
  } else {
    const isSmallScreen = window.innerWidth < 850; // Adjust the width threshold as needed

    // Set PDF format based on screen size
    const pdfFormat = isSmallScreen ? [1025, 2200] : [1000, 1500]; // Small size for small screens, larger for larger screens

    const pdf_Formate = {
      margin: 0,
      filename: "Azan-resume-builder.pdf",
      image: { type: "jpeg", quality: 1.0 },
      html2canvas: { scale: 3 },
      jsPDF: { unit: "px", format: pdfFormat, orientation: "portrait" },
    };

    html2pdf()
      .from(container2) // means downloaded  pdf comes from container2
      .set(pdf_Formate) // and the downloaded set according to this format
      .save();
  }
});

//! Shareable link button for resume
let params = new URLSearchParams({
  name: names.value,
  designation: designation.value,
  email: email.value,
  Linkedin: Linkedin.value,
  github: github.value,
  locations: locations.value,
  school: school.value,
  Degree: Degree.value,
  College: College.value,
  html: html.value,
  css: css.value,
  rjs: rjs.value,
  ty: ty.value,
  image: image.src,
  aboutMe: aboutMe.value,
  yearOfCollege: yearOfCollege.value,
  yearOfSchool: yearOfSchool.value,
  ph: ph.value,
  insitution: insitution.value,
  experience: experience.value,
});

let uniquePath = `${window.location.origin}? ${params.toString()}`; //link generated for each user  on the bases of it's data
console.log(uniquePath);
Linkbtn.addEventListener("click", () => {
  navigator.clipboard.writeText(uniquePath).then(() => {
    alert("Link Copied successfully");
  });
  window.history.replaceState(null, "", `${params.toString()}`);
});
//when user click on Linkbtn with the help of  window.Clipboard.writeText link automatically copied
